# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run SwiftLint"
  lane :lint do
    swiftlint(
      mode: :lint,
      strict: false,
      raise_if_swiftlint_error: false
    )
  end


  desc "Build app"
  lane :build do
    build_app(
      scheme: "NASAAPODApp",
      export_method: "development",
      clean: true,
      skip_codesigning: true
    )
  end

  desc "Run all tests"
  lane :test do
    lint
    run_tests(
      scheme: "NASAAPODApp",
      devices: ["iPhone 16"],  # Changed from iPhone 15 to iPhone 16
      clean: true
    )
  end

  desc "Full CI pipeline"
  lane :ci do
    lint
    test
    build
  end
end